import { config } from '../config/env';
import { dataStorage, UserMetricsSnapshot, Insight } from './dataStorage';

interface OpenAIChoice {
    message: {
        content: string;
    };
}

interface OpenAIResponse {
    choices: OpenAIChoice[];
}

const COACH_SYSTEM_PROMPT = `
You are a calm, supportive, and factual nutrition coach.
You are provided with a "User Metrics Snapshot" and a list of "Active Insights" generated by a deterministic rule engine.
Your goal is to explain these insights to the user or answer their specific question using ONLY this data.

GUARDRAILS:
1. Do NOT invent numbers. Use only the specific numbers in the snapshot (averages, goals, trends).
2. Do NOT reference specific meals or foods unless listed in 'commonFoods'. You do not have access to meal logs.
3. Do NOT diagnose medical conditions.
4. If the user asks something you cannot answer from the data, say "I don't have enough data to answer that."
5. Be concise. Avoid flowery language.
6. Return plain text only (no markdown, no bolding, no emojis).

MODES:
- "Daily Summary": Summarize the current status based on consistency and specific insights.
- "Weight Loss": Analyze the weight trend and consistency score.
- "Focus": Look at 'weakNutrients' and 'Active Insights' to suggest 1 action.

Tone: Professional, encouraging, but objective.
`;

const buildUserMessage = (snapshot: UserMetricsSnapshot, insights: Insight[], question?: string) => {
    const context = JSON.stringify({
        snapshot: {
            goals: snapshot.userGoals,
            averages: snapshot.averages7Day,
            weight: snapshot.weightTrend,
            consistency: snapshot.consistencyScore,
            streak: snapshot.currentStreak,
            weakNutrients: snapshot.weakNutrients,
            commonFoods: snapshot.commonFoods.map(f => f.name).join(', ')
        },
        activeInsights: insights.map(i => ({
            title: i.title,
            type: i.type,
            description: i.description,
            metric: i.relatedMetric
        }))
    });

    if (question) {
        return `Context: ${context}\n\nUser Question: "${question}"`;
    }

    return `Context: ${context}\n\nPlease provide a daily summary/check-in based on this data.`;
};

export const aiCoachService = {
    async getCoachResponse(userQuestion?: string): Promise<string> {
        const snapshot = await dataStorage.getUserMetricsSnapshot();
        const insights = await dataStorage.loadInsights();

        // Guardrail: No data
        if (!snapshot) {
            return "I don't have enough data to generate a coaching insight yet. Please complete your profile and log some meals.";
        }

        // Guardrail: No API Key (Offline/Dev mode text generation)
        if (!config.OPENAI_API_KEY || config.OPENAI_API_KEY.includes('your-key')) {
            // Deterministic fallback
            if (userQuestion?.toLowerCase().includes('weight')) {
                return `You are currently ${snapshot.weightTrend.change && snapshot.weightTrend.change < 0 ? 'down' : 'stable'} ${Math.abs(snapshot.weightTrend.change || 0)}kg over the last ${snapshot.weightTrend.periodDays} days. Consistency is ${snapshot.consistencyScore}%.`;
            }
            const topInsight = insights.length > 0 ? insights[0].description : "You're on track.";
            return `Your 7-day consistency is ${snapshot.consistencyScore}%. ${topInsight}`;
        }

        try {
            const messages = [
                { role: 'system', content: COACH_SYSTEM_PROMPT },
                { role: 'user', content: buildUserMessage(snapshot, insights, userQuestion) }
            ];

            const response = await fetch(config.API_ENDPOINTS.OPENAI, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${config.OPENAI_API_KEY}`,
                },
                body: JSON.stringify({
                    model: config.OPENAI_CONFIG.model || 'gpt-3.5-turbo',
                    messages,
                    temperature: 0.5,
                    max_tokens: 150,
                }),
            });

            if (!response.ok) {
                throw new Error(`AI API error: ${response.status}`);
            }

            const data: OpenAIResponse = await response.json();
            const content = data.choices[0]?.message?.content;
            return content || "I couldn't generate a response at this time.";

        } catch (error) {
            console.error('AI Coach Error:', error);
            return "I'm having trouble connecting to the coaching service right now.";
        }
    }
};
