import { invokeAI } from './aiProxyService';
import { dataStorage, UserMetricsSnapshot, Insight } from './dataStorage';

const COACH_SYSTEM_PROMPT = `
You are a direct, data-driven nutrition coach.
You are provided with a "User Metrics Snapshot" and a list of "Active Insights" generated by a deterministic rule engine.
Your goal is to explain these insights to the user or answer their specific question using ONLY this data.

GUARDRAILS:
1. Do NOT invent numbers. Use only the specific numbers in the snapshot.
2. Do NOT reference specific meals of foods unless listed in 'commonFoods'.
3. Do NOT diagnose medical conditions.
4. If you lack data, say "Insufficient data."
5. Be extremely concise. No pleasantries (e.g., "Hello", "Good job"). Get straight to the point.
6. Return plain text only (no markdown, no bolding, no emojis).

MODES:
- "Daily Summary": 1 sentence summarizing status based on consistency.
- "Weight Loss": State the weight trend and consistency score.
- "Focus": Suggest 1 specific action based on 'weakNutrients'.

Tone: Direct, objective, efficient.
`;

const buildUserMessage = (snapshot: UserMetricsSnapshot, insights: Insight[], question?: string) => {
    const context = JSON.stringify({
        snapshot: {
            goals: snapshot.userGoals,
            averages: snapshot.averages7Day,
            weight: snapshot.weightTrend,
            consistency: snapshot.consistencyScore,
            streak: snapshot.currentStreak,
            weakNutrients: snapshot.weakNutrients,
            commonFoods: snapshot.commonFoods.map(f => f.name).join(', ')
        },
        activeInsights: insights.map(i => ({
            title: i.title,
            type: i.type,
            description: i.description,
            metric: i.relatedMetric
        }))
    });

    if (question) {
        return `Context: ${context}\n\nUser Question: "${question}"`;
    }

    return `Context: ${context}\n\nPlease provide a daily summary/check-in based on this data.`;
};

export const aiCoachService = {
    async getCoachResponse(userQuestion?: string): Promise<string> {
        const snapshot = await dataStorage.getUserMetricsSnapshot();
        const insights = await dataStorage.loadInsights();

        // Guardrail: No data
        if (!snapshot) {
            return "I don't have enough data to generate a coaching insight yet. Please complete your profile and log some meals.";
        }

        try {
            const messages = [
                { role: 'system', content: COACH_SYSTEM_PROMPT },
                { role: 'user', content: buildUserMessage(snapshot, insights, userQuestion) }
            ];

            const data = await invokeAI({
                model: 'gpt-4',
                messages,
                temperature: 0.5,
                max_tokens: 150,
                call_type: 'ai-coach',
            });

            const content = data.choices[0]?.message?.content;
            return content || "I couldn't generate a response at this time.";

        } catch (error) {
            console.error('AI Coach Error:', error);
            return "I'm having trouble connecting to the coaching service right now.";
        }
    }
};
